# User data schema

"""
Please reference to submodels as required here a add the submodel schema accordingly
"""
type AssetAdministrationShell{
	idShort: String
	version: String
	revision: String
	aasId: String
	displayName: String
	description: String
	checksum: String
	assetInformation: [AssetInformation!]! @relationship(
	type: "assetInformation"
	direction: OUT
)
	dataId: ID!
}

type AssetInformation{
	dataId: ID!
	assetKind: AssetKind
	globalAssetId: String!
	string: String
	specificAssetId: [SpecificAssetId!]! @relationship(
	type: "specificAssetId"
	direction: OUT
)
}

enum AssetKind{
	Type
	Instance
}

type SpecificAssetId{
	dataId: ID!
	name: String
	value: String
}

enum metaType{
	FragmentReference
	Referable
	AnnotatedRelationshipElement
	BasicEventElement
	Blob
	Capability
	DataElement
	Entity
	BasicEventElementFile
	MultiLanguageProperty
	Property
	Operation
	Range
	RelationshipElement
	ReferenceElement
	SubmodelElement
	SubmodelElementCollection
	SubmodelElementList
	AssetAdministrationShell
	ConceptDescription
	Identifiable
	Submodel
	GlobalReference
}

"""
Not part of the AAS specification
"""
type Counter{
	fromDataId: String!
	toDataId: String!
	counter: String
	dataId: ID!
}
