# Submodel ContactInformations


type ContactInformations {
  dataId: ID!
  metaData: String
  metaType: metaType
  contactInformation: [ContactInformation!]! @relationship(type: "submodelElement" direction: OUT)
}

# SubmodelElementCollection
type ContactInformation {
  dataId: ID!
  metaData: String
  metaType: metaType
  RoleOfContactPerson: String
  NationalCode: String
  Language: String 
  TimeZone: String
  CityTown: String
  Company: String
  Department: String
  Phone: [Phone!]! @relationship(type: "submodelElement" direction: OUT)
  Fax: [Fax!]! @relationship(type: "submodelElement" direction: OUT)
  Email: [Email!]! @relationship(type: "submodelElement" direction: OUT)
  IPCommunication: [IPCommunication!]! @relationship(type: "submodelElement" direction: OUT)
  Street: String
  Zipcode: String
  POBox: String
  ZipCodeOfPOBox: String
  StateCounty: String
  NameOfContact: String
  FirstName: String
  MiddleNames: String
  Title: String
  AcademicTitle: String
  FurtherDetailsOfContact: String
  AddressOfAdditionalLink: String
}

# SubmodelElementCollection
type Phone {
  dataId: ID!
  metaData: String
  metaType: metaType
  TelephoneNumber: String
  TypeOfTelephone: String
  AvailableTime: String
}

# SubmodelElementCollection
type Fax {
  dataId: ID!
  metaData: String
  metaType: metaType
  FaxNumber: String
  TypeOfFaxNumber: String
}

# SubmodelElementCollection
type Email {
  dataId: ID!
  metaData: metaType
  EmailAddress: String!
  PublicKey: String
  TypeOfEmailAddress: String
  TypeOfPublicKey: String
}

# SubmodelElementCollection
type IPCommunication {
  dataId: ID!
  metaData: metaType
  AddressOfAdditionalLink: String 
  TypeOfCommunication: String
  AvailableTime: String
}

enum metaType {
  # siehe Details of the AAS Part1 Seite 84
  FragmentReference
  Referable
  AnnotatedRelationshipElement
  BasicEventElement
  Blob
  Capability
  DataElement
  Entity
  BasicEventElementFile
  MultiLanguageProperty
  Property
  Operation
  Range
  RelationshipElement
  ReferenceElement
  SubmodelElement
  SubmodelElementCollection
  SubmodelElementList
  AssetAdministrationShell
  ConceptDescription
  Identifiable
  Submodel
  GlobalReference
}