# AAS-connect complete GraphQL Schema

interface Datamodel{
	dataId: ID! @id
}

interface Metamodel{
	metaId: ID! @id
}

"""
Please reference to submodels as required here
"""
type AssetAdministrationShell implements Datamodel{
	idShort: String
	version: String
	revision: String
	aasId: String
	displayName: String
	description_en: String
	checksum: String
	assetInformation: [AssetInformation!]! @relationship(
	type: "assetInformation"
	direction: OUT
)
	dataId: ID! @id
	contactInformations: [ContactInformations!]! @relationship(
	type: "submodel"
	direction: OUT
)
}

type AssetInformation implements Datamodel{
	dataId: ID! @id
	assetKind: AssetKind
	globalAssetId: String!
	specificAssetId: [SpecificAssetId!]! @relationship(
	type: "specificAssetId"
	direction: OUT
)
}

enum AssetKind{
	Type
	Instance
	NotApplicable
}

enum MetaType{
	FragmentReference
	Referable
	AnnotatedRelationshipElement
	BasicEventElement
	Blob
	Capability
	DataElement
	Entity
	BasicEventElementFile
	MultiLanguageProperty
	Property
	Operation
	Range
	RelationshipElement
	ReferenceElement
	SubmodelElement
	SubmodelElementCollection
	SubmodelElementList
	AssetAdministrationShell
	ConceptDescription
	Identifiable
	Submodel
	GlobalReference
}

type SpecificAssetId implements Datamodel{
	dataId: ID! @id
	name: String
	value: String
}


"""
Not part of the AAS specification, AAS-connect specific
"""
type Counter{
	fromDataId: String!
	toDataId: String!
	counter: String
}

type Submodel implements Metamodel{
	metaId: ID! @id
	idShort: String
	semanticId: String
	submodelId: String
	version: String
	revision: String
	description_en: String
	submodelElementCollection: [SubmodelElementCollection!]! @relationship(
	type: "submodelElementCollection"
	direction: OUT
)
}

type SubmodelElementCollection implements Metamodel{
	metaId: ID! @id
	idShort: String
	version: String
	revision: String
	description_en: String
	semanticId: String
	isCaseOf: String
	property: [Property!]! @relationship(
	type: "property"
	direction: OUT
)
	multiLanguageProperty: [MultiLanguageProperty!]! @relationship(
	type: "multiLanguageProperty"
	direction: OUT
)
	submodelElementCollection: [SubmodelElementCollection!]! @relationship(
	type: "subModelElementCollection"
	direction: OUT
)
}

type Property implements Metamodel{
	metaId: ID! @id
	idShort: String
	version: String
	revision: String
	semanticId: String
	description_en: String
	isCaseOf: String
	valueType: String
}

type MultiLanguageProperty implements Metamodel{
	metaId: ID! @id
	idShort: String
	version: String
	revision: String
	semanticId: String
	description_en: String
	isCaseOf: String
}

enum Card{
	ZeroToOne
	ZeroToMany
	OneToOne
	OneToMany
	ManyToOne
	ManyToMany
}

"""
Not part of the AAS specification, AAS-connect specific
"""
type Cardinality{
	id: ID! @id
	fromIdShort: String
	toIdShort: String
	card: Card
}

type ContactInformations implements Datamodel @plural(
	value: "ContactInformationsMany"
){
	dataId: ID! @id
	metaId: String
	metaType: MetaType
	contactInformation: [ContactInformation!]! @relationship(
	type: "submodelElement"
	direction: OUT
)
}

type ContactInformation implements Datamodel @plural(
	value: "ContactInformationMany"
){
	dataId: ID! @id
	metaId: String
	metaType: MetaType
	RoleOfContactPerson_val: String
	RoleOfContactPerson_vId: String
	NationalCode_val: String
	NationalCode_vId: String
	Language_val: String
	Language_vId: String
	TimeZone_val: String
	TimeZone_vId: String
	CityTown_val: String
	CityTown_vId: String
	Company_val: String
	Company_vId: String
	Department_val: String
	Department_vId: String
	Phone: [Phone!]! @relationship(
	type: "submodelElement"
	direction: OUT
)
	Fax: [Fax!]! @relationship(
	type: "submodelElement"
	direction: OUT
)
	Email: [Email!]! @relationship(
	type: "submodelElement"
	direction: OUT
)
	ipCommunication: [IPCommunication!]! @relationship(
	type: "submodelElement"
	direction: OUT
)
	Street_val: String
	Street_vId: String
	Zipcode_val: String
	Zipcode_vId: String
	POBox_val: String
	POBox_vId: String
	ZipCodeOfPOBox_val: String
	ZipCodeOfPOBox_vId: String
	StateCounty_val: String
	StateCounty_vId: String
	NameOfContact_val: String
	NameOfContact_vId: String
	FirstName_val: String
	FirstName_vId: String
	MiddleNames_val: String
	MiddleNames_vId: String
	Title_val: String
	Title_vId: String
	AcademicTitle_val: String
	AcademicTitle_vId: String
	FurtherDetailsOfContact_val: String
	FurtherDetailsOfContact_vId: String
	AddressOfAdditionalLink_val: String
	AddressOfAdditionalLink_vId: String
}

type Phone implements Datamodel{
	dataId: ID! @id
	metaId: String
	metaType: MetaType
	TelephoneNumber_val: String
	TelephoneNumber_vId: String
	TypeOfTelephone_val: String
	TypeOfTelephone_vId: String
	AvailableTime_val: String
	AvailableTime_vId: String
}

type Fax implements Datamodel{
	dataId: ID! @id
	metaId: String
	metaType: MetaType
	FaxNumber_val: String
	FaxNumber_vId: String
	TypeOfFaxNumber_val: String
	TypeOfFaxNumber_vId: String
}

type Email implements Datamodel{
	dataId: ID! @id
	metaId: String
	metaType: MetaType
	EmailAddress_val: String
	EmailAddress_vId: String
	PublicKey_val: String
	PublicKey_vId: String
	TypeOfEmailAddress_val: String
	TypeOfEmailAddress_vId: String
	TypeOfPublicKey_val: String
	TypeOfPublicKey_vId: String
}

type IPCommunication implements Datamodel{
	dataId: ID! @id
	metaId: String
	metaType: MetaType
	AddressOfAdditionalLink_val: String
	AddressOfAdditionalLink_vId: String
	TypeOfCommunication_val: String
	TypeOfCommunication_vId: String
	AvailableTime_val: String
	AvailableTime_vId: String
}


